package com.nnois;

import java.util.List;

/** Parallel passages on civic life, nature, learning, and energy. */
public final class DemoTexts {
    private DemoTexts() { }
    public record Sample(String language, String target, String text) { }
    public static final List<Sample> SAMPLES = List.of(
        new Sample("eng", "river", "On Saturday morning, families walk through the city park beside the river. Children observe birds and trees while a teacher explains how clean water protects nature. Across the bridge, the public library welcomes students who read books about history, science, and music. Local farmers sell bread, fruit, and vegetables at the market. In the afternoon, residents discuss renewable energy, public transport, and the future of their community."),
        new Sample("ita", "fiume", "Il sabato mattina, le famiglie passeggiano nel parco della città accanto al fiume. I bambini osservano gli uccelli e gli alberi mentre un insegnante spiega come l'acqua pulita protegge la natura. Oltre il ponte, la biblioteca pubblica accoglie studenti che leggono libri di storia, scienza e musica. Gli agricoltori locali vendono pane, frutta e verdura al mercato. Nel pomeriggio, gli abitanti discutono di energia rinnovabile, trasporto pubblico e futuro della loro comunità."),
        new Sample("fra", "rivière", "Le samedi matin, les familles se promènent dans le parc de la ville près de la rivière. Les enfants observent les oiseaux et les arbres pendant qu'un enseignant explique comment l'eau propre protège la nature. De l'autre côté du pont, la bibliothèque publique accueille des étudiants qui lisent des livres sur l'histoire, la science et la musique. Les agriculteurs locaux vendent du pain, des fruits et des légumes au marché. L'après-midi, les habitants discutent des énergies renouvelables, des transports publics et de l'avenir de leur communauté."),
        new Sample("deu", "Fluss", "Am Samstagmorgen spazieren Familien durch den Stadtpark neben dem Fluss. Kinder beobachten Vögel und Bäume, während ein Lehrer erklärt, wie sauberes Wasser die Natur schützt. Auf der anderen Seite der Brücke empfängt die öffentliche Bibliothek Studenten, die Bücher über Geschichte, Wissenschaft und Musik lesen. Bauern aus der Region verkaufen Brot, Obst und Gemüse auf dem Markt. Am Nachmittag sprechen die Bewohner über erneuerbare Energie, öffentliche Verkehrsmittel und die Zukunft ihrer Gemeinschaft."),
        new Sample("spa", "río", "El sábado por la mañana, las familias pasean por el parque de la ciudad junto al río. Los niños observan aves y árboles mientras un profesor explica cómo el agua limpia protege la naturaleza. Al otro lado del puente, la biblioteca pública recibe a estudiantes que leen libros sobre historia, ciencia y música. Los agricultores locales venden pan, frutas y verduras en el mercado. Por la tarde, los vecinos hablan de energía renovable, transporte público y el futuro de su comunidad."),
        new Sample("por", "rio", "No sábado de manhã, as famílias passeiam pelo parque da cidade junto ao rio. As crianças observam pássaros e árvores enquanto um professor explica como a água limpa protege a natureza. Do outro lado da ponte, a biblioteca pública recebe estudantes que leem livros sobre história, ciência e música. Os agricultores locais vendem pão, frutas e legumes no mercado. À tarde, os moradores discutem energia renovável, transporte público e o futuro da sua comunidade."),
        new Sample("nld", "rivier", "Op zaterdagochtend wandelen gezinnen door het stadspark naast de rivier. Kinderen kijken naar vogels en bomen terwijl een leraar uitlegt hoe schoon water de natuur beschermt. Aan de andere kant van de brug ontvangt de openbare bibliotheek studenten die boeken over geschiedenis, wetenschap en muziek lezen. Lokale boeren verkopen brood, fruit en groenten op de markt. In de middag bespreken bewoners duurzame energie, openbaar vervoer en de toekomst van hun gemeenschap.")
    );
}
